### PR TITLE
Port over the VSX version

### PR DESCRIPTION
**Pull request by easyaspi314**
Supports both big and little endian.

### CODE REVIEW

**Comment by easyaspi314** [comment]
Hold on, don't merge yet, I want to double check in qemu.

**Comment by easyaspi314** [comment]
aaaaaaa oof.

Big Endian is borked right now.

**Comment by easyaspi314** [comment]
ok fixed 
will upload in a few once I clean it up
```
$ qemu-ppc64-static -cpu power9 xxhsum-ppc64 -b
xxhsum-ppc64 0.7.0 (64-bits ppc64 + VSX big endian), GCC 8.2.0, by Yann Collet
Sample of 100 KB...
XXH32               :     102400 ->    14043 it/s ( 1371.4 MB/s)
XXH32 unaligned     :     102400 ->    11567 it/s ( 1129.6 MB/s)
XXH64               :     102400 ->    32768 it/s ( 3200.0 MB/s)
XXH64 unaligned     :     102400 ->    28087 it/s ( 2742.9 MB/s)
XXH3_64bits         :     102400 ->     6146 it/s (  600.2 MB/s)
XXH3_64b unaligned  :     102400 ->     5958 it/s (  581.8 MB/s)
$ qemu-ppc64le-static -cpu power9 xxhsum-ppc64le -b
xxhsum-ppc64le 0.7.0 (64-bits ppc64 + VSX little endian), GCC 8.2.0, by Yann Collet
Sample of 100 KB...
XXH32               :     102400 ->    13528 it/s ( 1321.1 MB/s)
XXH32 unaligned     :     102400 ->    12485 it/s ( 1219.2 MB/s)
XXH64               :     102400 ->    32684 it/s ( 3191.8 MB/s)
XXH64 unaligned     :     102400 ->    32768 it/s ( 3200.0 MB/s)
XXH3_64bits         :     102400 ->    10923 it/s ( 1066.7 MB/s)
XXH3_64b unaligned  :     102400 ->     9665 it/s (  943.9 MB/s)
```
This is qemu,  so the VSX code is expected to run slowly. It is much faster on actual hardware.

**Comment by easyaspi314** [comment]
Done

**Comment by Cyan4973** [comment]
Thanks @easyaspi314, it's a great patch !

Just a little loosely related question :
the current Travis CI test setup is supposed to already test PPC support, 
and I expect it to test big endian path.

And your very first patch passes it perfectly : 
https://travis-ci.org/Cyan4973/xxHash/jobs/525110149

but since you said the big endian support was not working,
I'm now wondering if the PPC test on Travis CI actually works or not ?

**Comment by easyaspi314** [comment]
Well this only works on PPC64.

**Pull request merged**
