### PR TITLE
Remove stream loads and slightly improve avx512 seed generation

### PR DESCRIPTION
**Pull request by goldsteinn**
Streamed loads (`vmovntdqa`) don't provide any benefit over normal
aligned loads (`vmovdqa{8|16|32|64}`) but prevent GCC/Clang from
micro-fusing the loads with the ALU wasting code size.

Replace lane cross `vpbroadcastq` with vpsubq`

### CODE REVIEW

**Comment by Cyan4973** [comment]
I presume this change is expected to bring some improvements, either speed or binary size ?
Is there any way to measure such benefit ?

Also : `_mm256_stream_load_si256` was brought by @gzm55 as part of #351 . @gzm55: do you remember any specific reason to select this intrinsic variant, instead of the now proposed `_mm256_load_si256` ?

**Comment by goldsteinn** [comment]
> I presume this change is expected to bring some improvements, either speed or binary size ? Is there any way to measure such benefit ?



Size:
`-O3 -march=x86-64-v3`: Saves 124 bytes of `.text`
`-O3 -march=x86-64-v4`: Saves 88 bytes of `.text. 

Perf:

Intuitively there is no difference. The actual backend change (mask generation) is not in the loop.

`micro-fusion` doesn't save any backend uops. On some x86-64 machine it might be the difference
makers for a loop fitting in the DSB/LSD, but that's really not something you can control at the `C` level. 
The best I can say is it does give the compiler the flexibility to make those optimization as based on its 
model of the FE it can decide whether `micro-fusion` is worth it (although I don't know of any compiler 
that does that). Maybe it was save an icache miss occasionally but that's a stretch.



> 
> Also : `_mm256_stream_load_si256` was brought by @gzm55 as part of #351 . @gzm55: do you remember any specific reason to select this intrinsic variant, instead of the now proposed `_mm256_load_si256` ?

**Review by Cyan4973 — APPROVED** [review]

**Comment by gzm55** [comment]
> I presume this change is expected to bring some improvements, either speed or binary size ? Is there any way to measure such benefit ?
> 
> Also : `_mm256_stream_load_si256` was brought by @gzm55 as part of #351 . @gzm55: do you remember any specific reason to select this intrinsic variant, instead of the now proposed `_mm256_load_si256` ?

Logically two serials of load instructions are the same. `*_stream_*` intrinsics try to load with  non-temporal memory. When choosing load instructions, `micro-fusion` is not considered much, and these are the main reasons i can remember:
- the loaded data here should be read and process once, and
- the data will rarely be cached before load, so the non-temporal memory should be suiltable
- `_mm512_stream_load_si512` has a smaller latency than `_mm512_load_si512 ` from https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html
- many time benchmarks for avx2 and avx512, and the  `*_stream_*` intrinsics seams to be more stable (now the data were lost)

**Comment by goldsteinn** [comment]
> > I presume this change is expected to bring some improvements, either speed or binary size ? Is there any way to measure such benefit ?
> > Also : `_mm256_stream_load_si256` was brought by @gzm55 as part of #351 . @gzm55: do you remember any specific reason to select this intrinsic variant, instead of the now proposed `_mm256_load_si256` ?
> 
> Logically two serials of load instructions are the same. `*_stream_*` intrinsics try to load with non-temporal memory. When choosing load instructions, `micro-fusion` is not considered much, and these are the main reasons i can remember:
> 
> * the loaded data here should be read and process once, and
> * the data will rarely be cached before load, so the non-temporal memory should be suiltable

AFAIK this is only potentially meaningful for non-cacheable memory.
See: https://stackoverflow.com/questions/32103968/non-temporal-loads-and-the-hardware-prefetcher-do-they-work-together
and: https://stackoverflow.com/questions/35516878/acquire-release-semantics-with-non-temporal-stores-on-x64

> * `_mm512_stream_load_si512` has a smaller latency than `_mm512_load_si512 ` from https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html

This is an error in the intrinsics guides' documentation.

See https://uops.info/ for a generally more reliable source on these things.

Seems to also be an extra `uop` for the NT hint.


> * many time benchmarks for avx2 and avx512, and the  `*_stream_*` intrinsics seams to be more stable (now the data were lost)

**Comment by gzm55** [comment]
> > > I presume this change is expected to bring some improvements, either speed or binary size ? Is there any way to measure such benefit ?
> > > Also : `_mm256_stream_load_si256` was brought by @gzm55 as part of #351 . @gzm55: do you remember any specific reason to select this intrinsic variant, instead of the now proposed `_mm256_load_si256` ?
> > 
> > 
> > Logically two serials of load instructions are the same. `*_stream_*` intrinsics try to load with non-temporal memory. When choosing load instructions, `micro-fusion` is not considered much, and these are the main reasons i can remember:
> > 
> > * the loaded data here should be read and process once, and
> > * the data will rarely be cached before load, so the non-temporal memory should be suiltable
> 
> AFAIK this is only potentially meaningful for non-cacheable memory. See: https://stackoverflow.com/questions/32103968/non-temporal-loads-and-the-hardware-prefetcher-do-they-work-together and: https://stackoverflow.com/questions/35516878/acquire-release-semantics-with-non-temporal-stores-on-x64
> 
> > * `_mm512_stream_load_si512` has a smaller latency than `_mm512_load_si512 ` from https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html
> 
> This is an error in the intrinsics guides' documentation.
> 
> See https://uops.info/ for a generally more reliable source on these things.
> 
> Seems to also be an extra `uop` for the NT hint.
> 
> > * many time benchmarks for avx2 and avx512, and the  `*_stream_*` intrinsics seams to be more stable (now the data were lost)

@goldsteinn thanks for your explantation

**Pull request merged**
