### PR TITLE
Fix neon

### PR DESCRIPTION
**Pull request by hzhuang1**
Fix build issues related to NEON

### CODE REVIEW

**Comment by easyaspi314** [comment]
Isn't building for AArch64 without NEON a little odd? Aside from maybe osdev where you can't use FPU registers?

If you want to build the scalar version, just define `-DXXH_VECTOR=XXH_SCALAR`.

**Comment by easyaspi314** [comment]
> `Macro "__arm__" indicates armv7. Without it, "arm_neon.h" isn't included
for NEON.`

**Incorrect.** `__arm__` indicates ARM, not ARMv7. (It also doesn't detect Thumb mode).

If you compile for ARMv6, this would error, as `arm_neon.h` cannot be included without NEON support, unlike the SSE intrinsic headers.

The correct way to detect ARM NEON for ARMv7 is either `__ARM_NEON` or `__ARM_NEON__`, although `__aarch64__`, `_M_ARM` (MSVC ARMv7), and `_M_ARM64` indicate NEON support by default.

**Comment by hzhuang1** [comment]
> 
> The correct way to detect ARM NEON for ARMv7 is either `__ARM_NEON` or `__ARM_NEON__`, although `__aarch64__`, `_M_ARM` (MSVC ARMv7), and `_M_ARM64` indicate NEON support by default.

OK. Let me try.

**Comment by hzhuang1** [comment]
It's not urgent. Close it first.

**Pull request closed without merging**
