### PR TITLE
Visual Studio tests on Appveyor

### LINKED ISSUE #249: Warnings in xxh3.h on MSVC
I get this on AppVeyor when building with 0.7.1 and XXH_INLINE_ALL:
```
c:\projects\arrow\cpp\src\arrow\vendored\xxhash\xxh3.h(1372): error C2220: warning treated as error - no 'object' file generated
c:\projects\arrow\cpp\src\arrow\vendored\xxhash\xxh3.h(1372): warning C4146: unary minus operator applied to unsigned type, result still unsigned
c:\projects\arrow\cpp\src\arrow\vendored\xxhash\xxh3.h(1379): warning C4146: unary minus operator applied to unsigned type, result still unsigned
c:\projects\arrow\cpp\src\arrow\vendored\xxhash\xxh3.h(1383): warning C4146: unary minus operator applied to unsigned type, result still unsigned
```

### PR DESCRIPTION
**Pull request by Cyan4973**
now generates an error when Visual compiler emits a warning
also fix a few corresponding minor warnings on Visual.
fix #249

### CODE REVIEW

**Comment by Cyan4973** [comment]
Something is off. 

If I use `-DCMAKE_C_FLAGS=` for anything, then `xxhash.lib` is missing, and the linking stage fails.

**Comment by wesm** [comment]
Odd. I'll try to take a look at this in the next few days

**Comment by wesm** [comment]
Looking. Passing `CMAKE_C_FLAGS` indeed seems to suppress some other flags that were getting passed before

**Comment by wesm** [comment]
https://github.com/wesm/xxHash/commit/b38e507f232169f56ee1665656645d1814c1729c fixes it for me

**Comment by Cyan4973** [comment]
Yep, that works, thanks @wesm  !

**Pull request merged**
