### PR TITLE
xxh3: add NEON support

### PR DESCRIPTION
**Pull request by easyaspi314**
Signed-off-by: easyaspi314 (Devin) <easyaspi314@users.noreply.github.com>

### CODE REVIEW

**Comment by Cyan4973** [comment]
That's a great patch ! Thanks @easyaspi314 !

I'm going to test it on some ARM android devices.

**Comment by Cyan4973** [comment]
Quick test on my Samsung S7 (Qualcomm chip) using clang 7.0 on termux : 

XXH32 : 2 GB/s
XXH64 : 3.8 GB/s
XXH3 : 6.1 GB/s

Reasonably faster than XXH64, as I would expect, though less impressive than your own tests (reaching > 10 GB/s).

I've also been trying to compile this version in 32-bits mode (`-m32`).
It doesn't work : somewhere, in some deep library (`asm/sigcontext.h`), the `__uint128_t` type is needed, and this type is not defined for 32-bit platforms ...

**Comment by easyaspi314** [comment]
The hash seems less impressive on aarch64 for some reason.

Also, I think I am going to disable the NEON version on aarch64 GCC 6.x and earlier. It generates tons of loads and stores and the scalar version ends up being faster.

**Comment by easyaspi314** [comment]
[xxhsum.zip](https://github.com/Cyan4973/xxHash/files/2922400/xxhsum.zip)
Here is a binary I compiled for 32-bit on my phone in termux, and it gets the 10 GB/s on my phone. It *should* work on your phone as well.

**Comment by Cyan4973** [comment]
I tried to run this binary on `termux`, but it did not worked  : 
```
CANNOT LINK EXECUTABLE "./xxhsum": "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 64-bit instead of 32-bit                                                          
```

I'm not too surprised : it's always a total pain to run a binary built somewhere else on Linux.

At the very least, everything must be statically included in the binary (`-static`),
but even that may sometimes be impossible, depending on the build chain.

**Comment by easyaspi314** [comment]
Try doing this:
```
$ unset LD_PRELOAD
$ bash
$ ./xxhsum -b
```
If not, try running from ADB.

**Comment by Cyan4973** [comment]
> Try doing this:

Thanks, that works !

Here are some results : 
```
XXH32 : 3.3 GB/s
XXH64 : 1.1 GB/s
XXH3  : 7.9 GB/s
```

`XXH32` is (quite noticeably) faster (than `aarch64` version). That's surprising !
Could it be a compiler's impact ? Or is the 32-bits mode really different and faster for such workload ?

`XXH64` is slower, but that one was expected.

`XXH3` is a lot faster! Not yet 10 GB/s, but within striking distance, so I can definitely imagine a different CPU offering better performance and breaking this limit.

**Comment by easyaspi314** [comment]
It is mostly because of the changes in register layout. It ruins a lot of the old NEON tricks.


This is the code in XXH3_accumulate:
```c
#if !defined(__aarch64__) && !defined(__arm64__) && !defined(XXH_NO_ARM32_HACK)
            /* On 32-bit ARM, we can take advantage of the packed registers.
             * This is not portable to aarch64!
             * Basically, on 32-bit NEON, registers are stored like so:
             *  .----------------------------------.
             *  |                q8                | // uint32x4_t
             *  |-----------------.----------------|
             *  |  d16 (.val[0])  |  d17 (.val[1]) | // uint32x2x2_t
             *  '-----------------'----------------'
             * vld2.32 will store its values into two double registers, returning
             * a uint32x2_t. In NEON, this will be stored in, for example, d16 and d17.
             * Reinterpret cast it to a uint32x4_t and you get q8 for free
             *
             * On aarch64, this was changed completely.
             *
             * aarch64 gave us 16 more quad registers, but they also removed this behavior,
             * instead matching smaller registers to the lower sections of the higher
             * registers and zeroing the rest.
             *  .----------------------------------..---------------------------------.
             *  |               v8.4s              |               v9.4s               |
             *  |-----------------.----------------|-----------------.-----------------|
             *  | v8.2s (.val[0]) |     <zero>     | v9.2s (.val[1]) |      <zero>     |
             *  '-----------------'----------------'-----------------'-----------------'
             * On aarch64, ld2 will put it into v8.2s and v9.2s. Reinterpreting
             * is not going to help us here, as half of it will end up being zero.
             *
             * Even if it did, aarch64 apparently does really bad with shuffling, so
             * we use a different method. */

            uint32x2x2_t d = vld2_u32(xdata + i * 4);     /* load and swap */
            uint32x2x2_t k = vld2_u32(xkey + i * 4);
            /* Not sorry about breaking the strict aliasing rule.
             * Using a union causes GCC to spit out nonsense, but an alias cast
             * does not. */
            uint32x4_t const dk = vaddq_u32(*(uint32x4_t*)&d, *(uint32x4_t*)&k);  /* dk = d + k */
            xacc[i] = vmlal_u32(xacc[i], vget_low_u32(dk), vget_high_u32(dk));    /* xacc[i] += (U64)dkLo * (U64)dkHi; */
#elif OLD
            /* Portable, but slightly slower version */
            uint32x2x2_t const d = vld2_u32(xdata);
            uint32x2x2_t const k = vld2_u32(xkey);
            uint32x2_t const dkL = vadd_u32(d.val[0], k.val[0]);
            uint32x2_t const dkH = vadd_u32(d.val[1], k.val[1]);   /* uint32 dk[4]  = {d0+k0, d1+k1, d2+k2, d3+k3} */
            /* xacc must be aligned on 16 bytes boundaries */
            *xacc = vmlal_u32(*xacc, dkL, dkH);                /* uint64 res[2] = {dk0*dk1,dk2*dk3} */
#else
            /* A portable and aarch64-friendly version. It is slower on ARMv7a, though. */
            uint32x4_t d = vld1q_u32(xdata + i * 4);
            uint32x4_t k = vld1q_u32(xkey + i * 4);
            /* Add d and k, then reinterpret to a uint64x2_t. This is not a long add. */
            uint64x2_t dk = vreinterpretq_u64_u32(vaddq_u32(d, k));           /* dk = (U64)(d[1] + k[1]) << 32) | (d[0] + k[0]); */
            /* Long multiply high and low bits. */
            xacc[i] = vmlal_u32(xacc[i], vmovn_u64(dk), vshrn_n_u64(dk, 32)); /* xacc[i] += (dk & 0xFFFFFFFF) * (dk >> 32); */
#endif
```

Or in assembly:

ARM32 can do this in 6 instructions because of the packed registers (I explained above):
```asm
        vld2.32     { d16, d17 }, [r0]
        vld2.32     { d18, d19 }, [r1]
        vadd.i32    q8, q9, q8
        vld1.64     { d18, d19 }, [r2]
        vmlal.u32   q9, d16, d17
        vst1.64     { d18, d19 }, [r2]
```
aarch64 can't do this, because the higher bits of the register would be zero. Clang will generate `mov` instructions to fix it and GCC will store back to the stack, but it ends up besting 4 GB/s, and it is just UB.

aarch64 needs 7:
```asm
        ld2     { v0.2s, v1.2s }, [x0]
        ld2     { v2.2s, v3.2s }, [x1]
        ldr     q4, [x2]
        add     v5.2s, v2.2s, v0.2s
        add     v0.2s, v3.2s, v1.2s
        umlal   v4.2d, v5.2s, v0.2s
        str     q4, [x2]
```
or in ARMv7a syntax:
```asm
        vld2.32     { d16, d17 }, [r0 ]
        vld2.32     { d20, d21 }, [r1]
        vld1.64     { d18, d19 }, [r2]
        vadd.i32    d17, d21, d17
        vadd.i32    d16, d20, d16
        vmlal.u32   q9, d16, d17
        vst1.64     { d18, d19 }, [r2]
```
or 8 instructions which is seemingly faster on A57:
```asm
        ldr     q0, [x0]
        ldr     q1, [x1]
        ldr     q2, [x2]
        add     v0.4s, v1.4s, v0.4s
        xtn     v1.2s, v0.2d
        shrn    v0.2s, v0.2d, #32
        umlal   v2.2d, v1.2s, v0.2s
        str     q2, [x2]
```
in ARMv7a syntax:
```asm
        vld1.32     { d16, d17 }, [r0]
        vld1.32     { d18, d19 }, [r1]
        vld1.64     { d20, d21 }, [r2]
        vadd.i32    q8, q9, q8
        vmovn.i64   d16, q8
        vshrn.i64   d18, q8, #32
        vmlal.u32   q10, d16, d18
        vst1.64     { d20, d21 }, [r2]
```

Instruction meanings: 
`vld2.32/64`/`ld2` is that interleaved load, x86 equivalent:
```asm
    movqda   xmm0, xmmword ptr [ rax ]
    pshufd    xmm0, xmm0, 0xB1 # [ 0, 2, 1, 3 ]
```
`vmovn.i64`/`xtn` is basically `(U32)val`
`vshrn.i64`/`shrn` is shifting right then casting to U32
`vmlal.u32`/`umlal` is long unsigned multiply and add.
```asm
    pmuludq xmm0, xmm1
    paddq xmm3, xmm0
```
`vst1.64`/`str` is your average store.

aarch64, why did you have to take the fun out of NEON? :frowning:

**Comment by easyaspi314** [comment]
Unrelated, but this is the t1ha benchmark on my MacBook

clang 7
```
Build by Clang compiler 7.0 (self-check passed)
Testing t1ha2_atonce... Ok
Testing t1ha2_atonce128... Ok
Testing t1ha2_stream... Ok
Testing t1ha2_stream128... Ok
Testing t1ha1_64le... Ok
Testing t1ha1_64be... Ok
Testing t1ha0_32le... Ok
Testing t1ha0_32be... Ok
Testing t1ha0_ia32aes_noavx... Ok
Testing t1ha0_ia32aes_avx... Ok
Testing HighwayHash64_pure_c... Ok
Testing HighwayHash64_portable_cxx... Ok
Testing HighwayHash64_sse41... Ok
Testing StadtX... Ok

Preparing to benchmarking...
 - use RDTSCP as clock source for benchmarking
 - assume it cheap and floating (RESULTS MAY VARY AND BE USELESS)
 - measure granularity and overhead: 20 cycles, 0.05 iteration/cycle

Bench for tiny keys (7 bytes):
t1ha2_atonce            :     11.922 cycle/hash,  1.703 cycle/byte,  0.587 byte/cycle,  1.761 Gb/s @3GHz roughly
t1ha2_atonce128*        :     33.438 cycle/hash,  4.777 cycle/byte,  0.209 byte/cycle,  0.628 Gb/s @3GHz roughly
t1ha2_stream*           :     72.000 cycle/hash, 10.286 cycle/byte,  0.097 byte/cycle,  0.292 Gb/s @3GHz roughly
t1ha2_stream128*        :     89.000 cycle/hash, 12.714 cycle/byte,  0.079 byte/cycle,  0.236 Gb/s @3GHz roughly
t1ha1_64le              :     12.047 cycle/hash,  1.721 cycle/byte,  0.581 byte/cycle,  1.743 Gb/s @3GHz roughly
t1ha0                   :     13.344 cycle/hash,  1.906 cycle/byte,  0.525 byte/cycle,  1.574 Gb/s @3GHz roughly
xxhash32                :     18.750 cycle/hash,  2.679 cycle/byte,  0.373 byte/cycle,  1.120 Gb/s @3GHz roughly
xxhash64                :     20.938 cycle/hash,  2.991 cycle/byte,  0.334 byte/cycle,  1.003 Gb/s @3GHz roughly
xxh3                    :     13.891 cycle/hash,  1.984 cycle/byte,  0.504 byte/cycle,  1.512 Gb/s @3GHz roughly
meow                    :     17.969 cycle/hash,  2.567 cycle/byte,  0.390 byte/cycle,  1.169 Gb/s @3GHz roughly
StadtX                  :     18.938 cycle/hash,  2.705 cycle/byte,  0.370 byte/cycle,  1.109 Gb/s @3GHz roughly
HighwayHash64_pure_c    :    484.000 cycle/hash, 69.143 cycle/byte,  0.014 byte/cycle,  0.043 Gb/s @3GHz roughly
HighwayHash64_portable  :    429.000 cycle/hash, 61.286 cycle/byte,  0.016 byte/cycle,  0.049 Gb/s @3GHz roughly
HighwayHash64_sse41     :     66.125 cycle/hash,  9.446 cycle/byte,  0.106 byte/cycle,  0.318 Gb/s @3GHz roughly

Bench for large keys (16384 bytes):
t1ha2_atonce            :   3580.000 cycle/hash,  0.219 cycle/byte,  4.577 byte/cycle, 13.730 Gb/s @3GHz roughly
t1ha2_atonce128*        :   3584.000 cycle/hash,  0.219 cycle/byte,  4.571 byte/cycle, 13.714 Gb/s @3GHz roughly
t1ha2_stream*           :   3344.000 cycle/hash,  0.204 cycle/byte,  4.900 byte/cycle, 14.699 Gb/s @3GHz roughly
t1ha2_stream128*        :   3354.000 cycle/hash,  0.205 cycle/byte,  4.885 byte/cycle, 14.655 Gb/s @3GHz roughly
t1ha1_64le              :   3432.000 cycle/hash,  0.209 cycle/byte,  4.774 byte/cycle, 14.322 Gb/s @3GHz roughly
t1ha0                   :   1180.000 cycle/hash,  0.072 cycle/byte, 13.885 byte/cycle, 41.654 Gb/s @3GHz roughly
xxhash32                :   5758.000 cycle/hash,  0.351 cycle/byte,  2.845 byte/cycle,  8.536 Gb/s @3GHz roughly
xxhash64                :   3142.000 cycle/hash,  0.192 cycle/byte,  5.215 byte/cycle, 15.644 Gb/s @3GHz roughly
xxh3                    :   1544.000 cycle/hash,  0.094 cycle/byte, 10.611 byte/cycle, 31.834 Gb/s @3GHz roughly
meow                    :   1436.000 cycle/hash,  0.088 cycle/byte, 11.409 byte/cycle, 34.228 Gb/s @3GHz roughly
StadtX                  :   3616.000 cycle/hash,  0.221 cycle/byte,  4.531 byte/cycle, 13.593 Gb/s @3GHz roughly
HighwayHash64_pure_c    :  43844.000 cycle/hash,  2.676 cycle/byte,  0.374 byte/cycle,  1.121 Gb/s @3GHz roughly
HighwayHash64_portable  :  36330.000 cycle/hash,  2.217 cycle/byte,  0.451 byte/cycle,  1.353 Gb/s @3GHz roughly
HighwayHash64_sse41     :   3930.000 cycle/hash,  0.240 cycle/byte,  4.169 byte/cycle, 12.507 Gb/s @3GHz roughly
```
gcc 8.2
```
Build by GNU C/C++ compiler 8.2 (self-check passed)
Testing t1ha2_atonce... Ok
Testing t1ha2_atonce128... Ok
Testing t1ha2_stream... Ok
Testing t1ha2_stream128... Ok
Testing t1ha1_64le... Ok
Testing t1ha1_64be... Ok
Testing t1ha0_32le... Ok
Testing t1ha0_32be... Ok
Testing t1ha0_ia32aes_noavx... Ok
Testing t1ha0_ia32aes_avx... Ok
Testing HighwayHash64_pure_c... Ok
Testing HighwayHash64_portable_cxx... Ok
Testing HighwayHash64_sse41... Ok
Testing StadtX... Ok

Preparing to benchmarking...
 - use RDTSCP as clock source for benchmarking
 - assume it cheap and floating (RESULTS MAY VARY AND BE USELESS)
 - measure granularity and overhead: 20 cycles, 0.05 iteration/cycle

Bench for tiny keys (7 bytes):
t1ha2_atonce            :     14.922 cycle/hash,  2.132 cycle/byte,  0.469 byte/cycle,  1.407 Gb/s @3GHz roughly
t1ha2_atonce128*        :     35.375 cycle/hash,  5.054 cycle/byte,  0.198 byte/cycle,  0.594 Gb/s @3GHz roughly
t1ha2_stream*           :     59.438 cycle/hash,  8.491 cycle/byte,  0.118 byte/cycle,  0.353 Gb/s @3GHz roughly
t1ha2_stream128*        :     74.125 cycle/hash, 10.589 cycle/byte,  0.094 byte/cycle,  0.283 Gb/s @3GHz roughly
t1ha1_64le              :     15.172 cycle/hash,  2.167 cycle/byte,  0.461 byte/cycle,  1.384 Gb/s @3GHz roughly
t1ha0                   :     13.562 cycle/hash,  1.938 cycle/byte,  0.516 byte/cycle,  1.548 Gb/s @3GHz roughly
xxhash32                :     17.938 cycle/hash,  2.562 cycle/byte,  0.390 byte/cycle,  1.171 Gb/s @3GHz roughly
xxhash64                :     22.426 cycle/hash,  3.204 cycle/byte,  0.312 byte/cycle,  0.936 Gb/s @3GHz roughly
xxh3                    :     10.516 cycle/hash,  1.502 cycle/byte,  0.666 byte/cycle,  1.997 Gb/s @3GHz roughly
meow                    :     19.594 cycle/hash,  2.799 cycle/byte,  0.357 byte/cycle,  1.072 Gb/s @3GHz roughly
StadtX                  :     18.500 cycle/hash,  2.643 cycle/byte,  0.378 byte/cycle,  1.135 Gb/s @3GHz roughly
HighwayHash64_pure_c    :    501.500 cycle/hash, 71.643 cycle/byte,  0.014 byte/cycle,  0.042 Gb/s @3GHz roughly
HighwayHash64_portable  :    386.000 cycle/hash, 55.143 cycle/byte,  0.018 byte/cycle,  0.054 Gb/s @3GHz roughly
HighwayHash64_sse41     :     55.688 cycle/hash,  7.955 cycle/byte,  0.126 byte/cycle,  0.377 Gb/s @3GHz roughly

Bench for large keys (16384 bytes):
t1ha2_atonce            :   3942.000 cycle/hash,  0.241 cycle/byte,  4.156 byte/cycle, 12.469 Gb/s @3GHz roughly
t1ha2_atonce128*        :   4012.000 cycle/hash,  0.245 cycle/byte,  4.084 byte/cycle, 12.251 Gb/s @3GHz roughly
t1ha2_stream*           :   3824.000 cycle/hash,  0.233 cycle/byte,  4.285 byte/cycle, 12.854 Gb/s @3GHz roughly
t1ha2_stream128*        :   3832.000 cycle/hash,  0.234 cycle/byte,  4.276 byte/cycle, 12.827 Gb/s @3GHz roughly
t1ha1_64le              :   3422.000 cycle/hash,  0.209 cycle/byte,  4.788 byte/cycle, 14.364 Gb/s @3GHz roughly
t1ha0                   :   1210.000 cycle/hash,  0.074 cycle/byte, 13.540 byte/cycle, 40.621 Gb/s @3GHz roughly
xxhash32                :   5820.000 cycle/hash,  0.355 cycle/byte,  2.815 byte/cycle,  8.445 Gb/s @3GHz roughly
xxhash64                :   2966.000 cycle/hash,  0.181 cycle/byte,  5.524 byte/cycle, 16.572 Gb/s @3GHz roughly
xxh3                    :   2016.000 cycle/hash,  0.123 cycle/byte,  8.127 byte/cycle, 24.381 Gb/s @3GHz roughly
meow                    :   1436.000 cycle/hash,  0.088 cycle/byte, 11.409 byte/cycle, 34.228 Gb/s @3GHz roughly
StadtX                  :   3506.000 cycle/hash,  0.214 cycle/byte,  4.673 byte/cycle, 14.019 Gb/s @3GHz roughly
HighwayHash64_pure_c    :  42612.000 cycle/hash,  2.601 cycle/byte,  0.384 byte/cycle,  1.153 Gb/s @3GHz roughly
HighwayHash64_portable  :  36706.000 cycle/hash,  2.240 cycle/byte,  0.446 byte/cycle,  1.339 Gb/s @3GHz roughly
HighwayHash64_sse41     :   4469.959 cycle/hash,  0.273 cycle/byte,  3.665 byte/cycle, 10.996 Gb/s @3GHz roughly
```

However, disable SSE4.2 and XXH3 *completely flattens the competition.*
```
Build by Clang compiler 7.0 (self-check passed)
Testing t1ha2_atonce... Ok
Testing t1ha2_atonce128... Ok
Testing t1ha2_stream... Ok
Testing t1ha2_stream128... Ok
Testing t1ha1_64le... Ok
Testing t1ha1_64be... Ok
Testing t1ha0_32le... Ok
Testing t1ha0_32be... Ok
Testing t1ha0_ia32aes_noavx... Ok
Testing t1ha0_ia32aes_avx... Ok
Testing HighwayHash64_pure_c... Ok
Testing HighwayHash64_portable_cxx... Ok
Testing HighwayHash64_sse41... Ok
Testing StadtX... Ok

Preparing to benchmarking...
 - use RDTSCP as clock source for benchmarking
 - assume it cheap and floating (RESULTS MAY VARY AND BE USELESS)
 - measure granularity and overhead: 28 cycles, 0.0357143 iteration/cycle

Bench for tiny keys (7 bytes):
t1ha2_atonce            :     13.234 cycle/hash,  1.891 cycle/byte,  0.529 byte/cycle,  1.587 Gb/s @3GHz roughly
t1ha2_atonce128*        :     37.312 cycle/hash,  5.330 cycle/byte,  0.188 byte/cycle,  0.563 Gb/s @3GHz roughly
t1ha2_stream*           :     71.875 cycle/hash, 10.268 cycle/byte,  0.097 byte/cycle,  0.292 Gb/s @3GHz roughly
t1ha2_stream128*        :     89.500 cycle/hash, 12.786 cycle/byte,  0.078 byte/cycle,  0.235 Gb/s @3GHz roughly
t1ha1_64le              :     13.219 cycle/hash,  1.888 cycle/byte,  0.530 byte/cycle,  1.589 Gb/s @3GHz roughly
t1ha0                   :     13.891 cycle/hash,  1.984 cycle/byte,  0.504 byte/cycle,  1.512 Gb/s @3GHz roughly
xxhash32                :     19.656 cycle/hash,  2.808 cycle/byte,  0.356 byte/cycle,  1.068 Gb/s @3GHz roughly
xxhash64                :     21.500 cycle/hash,  3.071 cycle/byte,  0.326 byte/cycle,  0.977 Gb/s @3GHz roughly
xxh3                    :     14.547 cycle/hash,  2.078 cycle/byte,  0.481 byte/cycle,  1.444 Gb/s @3GHz roughly
meow                    :    190.000 cycle/hash, 27.143 cycle/byte,  0.037 byte/cycle,  0.111 Gb/s @3GHz roughly
StadtX                  :     21.594 cycle/hash,  3.085 cycle/byte,  0.324 byte/cycle,  0.973 Gb/s @3GHz roughly
HighwayHash64_pure_c    :    468.500 cycle/hash, 66.929 cycle/byte,  0.015 byte/cycle,  0.045 Gb/s @3GHz roughly
HighwayHash64_portable  :    414.000 cycle/hash, 59.143 cycle/byte,  0.017 byte/cycle,  0.051 Gb/s @3GHz roughly
HighwayHash64_sse41     :     71.500 cycle/hash, 10.214 cycle/byte,  0.098 byte/cycle,  0.294 Gb/s @3GHz roughly

Bench for large keys (16384 bytes):
t1ha2_atonce            :   4010.000 cycle/hash,  0.245 cycle/byte,  4.086 byte/cycle, 12.257 Gb/s @3GHz roughly
t1ha2_atonce128*        :   4122.000 cycle/hash,  0.252 cycle/byte,  3.975 byte/cycle, 11.924 Gb/s @3GHz roughly
t1ha2_stream*           :   3692.000 cycle/hash,  0.225 cycle/byte,  4.438 byte/cycle, 13.313 Gb/s @3GHz roughly
t1ha2_stream128*        :   3694.000 cycle/hash,  0.225 cycle/byte,  4.435 byte/cycle, 13.306 Gb/s @3GHz roughly
t1ha1_64le              :   3986.000 cycle/hash,  0.243 cycle/byte,  4.110 byte/cycle, 12.331 Gb/s @3GHz roughly
t1ha0                   :   3984.000 cycle/hash,  0.243 cycle/byte,  4.112 byte/cycle, 12.337 Gb/s @3GHz roughly
xxhash32                :   6562.000 cycle/hash,  0.401 cycle/byte,  2.497 byte/cycle,  7.490 Gb/s @3GHz roughly
xxhash64                :   3766.000 cycle/hash,  0.230 cycle/byte,  4.351 byte/cycle, 13.052 Gb/s @3GHz roughly
xxh3                    :   1608.000 cycle/hash,  0.098 cycle/byte, 10.189 byte/cycle, 30.567 Gb/s @3GHz roughly
meow                    :  19180.000 cycle/hash,  1.171 cycle/byte,  0.854 byte/cycle,  2.563 Gb/s @3GHz roughly
StadtX                  :   4216.000 cycle/hash,  0.257 cycle/byte,  3.886 byte/cycle, 11.658 Gb/s @3GHz roughly
HighwayHash64_pure_c    :  43922.000 cycle/hash,  2.681 cycle/byte,  0.373 byte/cycle,  1.119 Gb/s @3GHz roughly
HighwayHash64_portable  :  40542.000 cycle/hash,  2.474 cycle/byte,  0.404 byte/cycle,  1.212 Gb/s @3GHz roughly
HighwayHash64_sse41     :   5846.000 cycle/hash,  0.357 cycle/byte,  2.803 byte/cycle,  8.408 Gb/s @3GHz roughly
```

**Comment by Cyan4973** [comment]
Thanks for feedback @easyaspi314 !

These results feel in line with other measurements, which is a good sign.

I'm currently working on a new benchmark program, dedicated to measuring speed on short inputs.

What this work learned me so far : 
- Variable input size is *a lot* different than fixed input size, as it stresses internal branches a lot more. Ranking varies wildly depending on this condition. Dedicated care on this topic pays off. 
- Throughput is different from latency : throughput is when hashing a lot of things in batch mode, which is typically what benchmark do. But in real-life scenarios, hashing is often an isolated operation sandwiched between other piece of codes. In which case, latency matters a lot more. And it's way harder to measure ... It also shuffles the ranking considerably, and it's worth observing.
- Some algorithms cheat on quality. I created an [extended version of SMHasher](https://github.com/Cyan4973/smhasher) to check those cases. It costs a lot more time to run, but give higher confidence in the outcome.

I will try to publish something when it's ready. These tools have been essential in the design phase of `xxh3`.

**Pull request merged**
