### PR TITLE
ARM SVE optimization

### PR DESCRIPTION
**Pull request by hzhuang1**
It's used to replace pull request #713.

### CODE REVIEW

**Comment by hzhuang1** [comment]
How about this pull request? Is it ready to be merged?

**Comment by Cyan4973** [comment]
It probably is.
But it's also a pretty large diff.
I want to take some time to review it.
I've been lacking availability to do so, but I hope I'll be able to in the not-distant future.

**Comment by t-mat** [comment]
Hi @hzhuang1,

I silently :+1: for your Arm-SVE PRs.  But I also have witnessed that you've been having difficulty to land your PRs.

I suppose that since Yann didn't have any chance to play with Arm-SVE environment, he also has difficulty to (deeply) understand your changesets.  I'm sure that he must completely understand your changesets before mering them.

So I think perhaps you can choose so called "divide and conquer" PR strategy to achieve your goal faster.

I mean:

(I-1) Post dedicated (long-term) issue for Arm-SVE.
(I-2) In I-1, (re-)show big picture of your goal/intention.  And future maintainability of your changesets.
(PR-1s) Send serie of small/simple PRs (changesets).
(PR-2) Since your Arm-SVE PRs (PR-1) are small, Yann will be able to understand/judge/discuss your PRs step by step.  It'll be time consuming process.  But overall, helping him to understand your intentions/PRs will accelerate the landing process of Arm-SVE PRs.

**Comment by hzhuang1** [comment]
> Hi @hzhuang1,
> 
> I silently 👍 for your Arm-SVE PRs. But I also have witnessed that you've been having difficulty to land your PRs.
> 
> I suppose that since Yann didn't have any chance to play with Arm-SVE environment, he also has difficulty to (deeply) understand your changesets. I'm sure that he must completely understand your changesets before mering them.
> 
> So I think perhaps you can choose so called "divide and conquer" PR strategy to achieve your goal faster.
> 
> I mean:
> 
> (I-1) Post dedicated (long-term) issue for Arm-SVE. (I-2) In I-1, (re-)show big picture of your goal/intention. And future maintainability of your changesets. (PR-1s) Send serie of small/simple PRs (changesets). (PR-2) Since your Arm-SVE PRs (PR-1) are small, Yann will be able to understand/judge/discuss your PRs step by step. It'll be time consuming process. But overall, helping him to understand your intentions/PRs will accelerate the landing process of Arm-SVE PRs.

Thanks. I'll create the long-term issue first.

**Comment by hzhuang1** [comment]
Some SVE patches have been merged already. The rest patches are located in #762.

This pull request is out of date. So close it now.

**Pull request closed without merging**
