### PR TITLE
Don't Be The Compiler: Reroll len_17to128

### PR DESCRIPTION
**Pull request by easyaspi314**
The manual unroll was difficult to read and difficult to optimize.

Humans like readable loops, and compilers are written by humans.

This seems to actually improve performance, and it allows better size
optimizations as well.

### CODE REVIEW

**Comment by Cyan4973** [comment]
> This seems to actually improve performance

Do you have performance figures ?

**Comment by Cyan4973** [comment]
On my test system (i7-9700k, gcc v8.3.0), this patch seems to result in a steep performance decline : 

| | `dev` | `reroll_midrange` |
| --- | --- | --- |
| XXH3_64bits, len=128 | 15.2 GB/s | 10.2 GB/s |
| XXH3_64bits, len=64 | 12.2 GB/s | 7.5 GB/s |
| XXH3_128bits, len=128 | 10.7 GB/s | 9.1 GB/s |
| XXH3_128bits, len=64 | 8.2 GB/s | 6.6 GB/s |

**Comment by easyaspi314** [comment]
Oh, that's not right.

I'm going to close it for now. I need to investigate more.

**Comment by easyaspi314** [comment]
@Cyan4973 try this
```c


XXH_FORCE_INLINE XXH64_hash_t
XXH3_len_17to128_64b(const BYTE* XXH_RESTRICT input, size_t len,
                     const BYTE* XXH_RESTRICT secret, size_t secretSize,
                     XXH64_hash_t seed)
{
    size_t max = ((len - 1) & 0x60) / 32 /* ((len - 1) / 32) * 16 */, i;
    U64 acc = len * PRIME64_1;
    const BYTE *inpRev = input + (len - 16);
    XXH_ASSERT(secretSize >= XXH3_SECRET_SIZE_MIN); (void)secretSize;
    XXH_ASSERT(16 < len && len <= 128);
    for (i = 0; i <= max; i++) {
        /* input + (16 * i),            secret + (32 * i) */
        acc += XXH3_mix16B(input,  secret, seed);
        /* input + len - (16 * i) - 16, secret + (32 * i) + 16 */
        acc += XXH3_mix16B(inpRev, secret + 16, seed);
        input += 16; inpRev -= 16;  secret += 32;
    }
    return XXH3_avalanche(acc);
}
```

**Comment by Cyan4973** [comment]
In term of performance, that's closer : 

| | `dev` | `test` |
| --- | --- | --- |
| XXH3_64bits, len=100 | 16.8 GB/s | 16.4 GB/s |

However, I don't find the suggested variant more "readable" than the original one.

**Comment by easyaspi314** [comment]
Well yeah

But it absolutely domininates on aarch64
3.6 GB/s vs 3.3 GB/s for Len = 128

**Pull request closed without merging**
