### PR TITLE
added support for C and CPP [[fallthrough]] attribute

### PR DESCRIPTION
**Pull request by TheNicker**

### CODE REVIEW

**Comment by TheNicker** [comment]
Fixes issue #552

**Comment by t-mat** [comment]
Hi @TheNicker, the intention of this PR is very good since it helps static analysis.  But it seems there're some issues.

I'm supposing you're using `gcc-10` or greater, but this PR fails to pass our tests with `gcc-9` or earlier unfortunately.

You can reproduce these failures with the following commands.

```sh
cd
git clone https://github.com/Cyan4973/xxHash.git xxHash-pull-553
cd xxHash-pull-553
git fetch origin pull/553/head:pull_553
git checkout pull_553
git log -1
CC='gcc-9'  make clean xxhsum  # FAIL
CC='gcc-10' make clean xxhsum  # PASS
```

The reason is, when compiling *C code* with `gcc-9`

- It doesn't define `__has_c_attribute()`.  Because it `gcc` as a C compiler doesn't support it.
- But it *defines* `__has_cpp_attribute()` for *C code*.  And `__has_cpp_attribute(fallthrough)` returns `!0`.  But since the code itself is compiled as a *C code*, actual C code compilation procedure fails to understand `[[fallthrough]]`.

Honestly, I don't understand why `gcc` defines `__has_cpp_attribute()` and returns `!0` for C code.  All `__has_cpp_attribute()` must be failed for C code.

But we must deal with it.  For example,

```cpp
-	#elif defined(__has_cpp_attribute)
+	#elif defined(__has_cpp_attribute) && defined(__cplusplus)
	#   if __has_cpp_attribute(fallthrough)
	#       define XXH_FALLTHROUGH [[fallthrough]]
	#   endif
```

----

I also noticed that definition of `XXH_FALLTHROUGH` is within `#ifndef XXH_NO_LONG_LONG` block.  This PR fails the following test

```sh
CC='gcc-10' make clean c90test  # FAIL
```

Please replace the definition at the outside of the `XXH_NO_LONG_LONG` block.

----

To complete the test, please run the following commands

```sh
CC='gcc-9'  make clean test
CC='gcc-10' make clean test
```

**Comment by t-mat** [comment]
For older version of `gcc`, `/* fallthrough */` is a special comment for [-Wimplicit-fallthrough](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-fallthrough).

Please leave them as a comment.

```c
           case 12:      XXH_PROCESS4;
                         XXH_FALLTHROUGH; /* fallthrough */
```

**Comment by TheNicker** [comment]
> For older version of gcc, /* fallthrough */ is a special comment for -Wimplicit-fallthrough.
Please leave them as a comment.

I've [added special case, line 568](https://github.com/Cyan4973/xxHash/pull/553/files#diff-343c0b024b7734da2547ae51a138702bd0bb2f2adc2bc7fb7eb97b6d543e9785R568) for old compilers, no warnings now.

I can see that precious time is being spent on supporting old compilers.

Does someone even use it ? C90  with xxhash ?

I've had to pull out from the garret my old 286 XT to fix these issues.  :wink:

**Review by Cyan4973 — APPROVED** [review]

**Pull request merged**
