### PR TITLE
CI: fix missing space

### PR DESCRIPTION
**Pull request by hzhuang1**
Missing space caused that github action doesn't work.

Signed-off-by: Haojian Zhuang <haojian.zhuang@linaro.org>

### CODE REVIEW

**Comment by t-mat** [comment]
Thanks.  It's working now 🎉 

image

**Comment by hzhuang1** [comment]
> Thanks. It's working now 🎉
> 
> image

Thanks for your guide. Whatever it's the issue that is imported by me.

**Comment by hzhuang1** [comment]
Screen Shot 2022-11-10 at 10 42 4@t-mat

@t-mat Oh, there's still a tipi issue.

**Comment by t-mat** [comment]
Right.  It seems tipi.build system is still hitting some issue. 😿 

https://github.com/Cyan4973/xxHash/actions/runs/3433505455/jobs/5723893397#step:8:10075

image


@Cyan4973 can we comment out tipi.build for now?

edit:
Our status
- This PR fixes YAML syntax error in `ci.yml`.
- Now GitHub actions is working properly.
- But tipi.build test is failing with different and misterious error.

**Comment by Cyan4973** [comment]
I believe tipi.build should not be part of `xxHash` CI test suite.
We shall remove it.

**Comment by Cyan4973** [comment]
Thanks for finding and fixing the core issue @hzhuang1 !

**Review by Cyan4973 — APPROVED** [review]

**Pull request merged**
