### PR TITLE
[WIP] Doxygen and more detailed documentation

### PR DESCRIPTION
**Pull request by easyaspi314**
XXH32's API, XXH*_state_s, the config macros, and some other things are documented in Doxygen format, and a basic (albeit messy for now) Doxyfile was added.

Some things were also [re]documented in detail.

Still need to work on structuring the main page (set it to README.md?), and cleaning things up. 

How to view the docs for now:

```
 $ sudo apt install doxygen
 $ npm install -g http-server # or you can use LLVM's scan-view
 $ doxygen && hs doxygen/html -s -c-1 -o # will open a browser
```

### CODE REVIEW

**Review by Cyan4973 — APPROVED** [review]
Thanks @easyaspi314 ! Looks great !

**Comment by easyaspi314** [comment]
Noticed some typos, I will go fix those

**Comment by easyaspi314** [comment]
RIP s390x

**Comment by easyaspi314** [comment]
Light documentation on XXH32's internals is done. Mostly just copied from the spec. 😛

**Comment by easyaspi314** [comment]
Ok I think this is ready. Doxyfile is now clean and doesn't use the sample as a base.

**Review by Cyan4973 — APPROVED** [review]

**Pull request merged**
