### PR TITLE
xxhsum: split sanity check

### PR DESCRIPTION
**Pull request by easyaspi314**
It now exists in `xsum_sanity_check.c`

Also add `XSUM_NO_TESTS` option, which instead prints "`This version of xxhsum is not verified.`" to `stderr` whenever `XSUM_sanityCheck()` is called.

By the way, since we are refactoring, should I turn it into a static table instead of a chain of function calls like I did for the benchmark? It will reduce code size a good amount.

### CODE REVIEW

**Comment by easyaspi314** [comment]
Yes, this looks quite nice
```c
static const XSUM_testdata64_t XSUM_XXH64_testdata[] = {
    { 1,      0,       0, 0xEF46DB3751D8E999ULL },
    { 1,      0, PRIME32, 0xAC75FDA2929B17EFULL },
    { 0,      1,       0, 0xE934A84ADB052768ULL },
    { 0,      1, PRIME32, 0x5014607643A9B4C3ULL },
    { 0,      4,       0, 0x9136A0DCA57457EEULL },
    { 0,     14,       0, 0x8282DCC4994E35C8ULL },
    { 0,     14, PRIME32, 0xC3BD6BF63DEB6DF0ULL },
    { 0,    222,       0, 0xB641AE8CB691C174ULL },
    { 0,    222, PRIME32, 0x20CB8AB7AE10C14AULL },
};

static const XSUM_testdata64_t XSUM_XXH3_testdata[] = {
    { 1,      0,       0, 0x2D06800538D394C2ULL },  /* empty string */
    { 1,      0, PRIME64, 0xA8A6B918B2F0364AULL },  /* empty string */
    { 0,      1,       0, 0xC44BDFF4074EECDBULL },  /*  1 -  3 */
    { 0,      1, PRIME64, 0x032BE332DD766EF8ULL },  /*  1 -  3 */
    { 0,      6,       0, 0x27B56A84CD2D7325ULL },  /*  4 -  8 */
    { 0,      6, PRIME64, 0x84589C116AB59AB9ULL },  /*  4 -  8 */
    { 0,     12,       0, 0xA713DAF0DFBB77E7ULL },  /*  9 - 16 */
    { 0,     12, PRIME64, 0xE7303E1B2336DE0EULL },  /*  9 - 16 */
    { 0,     24,       0, 0xA3FE70BF9D3510EBULL },  /* 17 - 32 */
    { 0,     24, PRIME64, 0x850E80FC35BDD690ULL },  /* 17 - 32 */
    { 0,     48,       0, 0x397DA259ECBA1F11ULL },  /* 33 - 64 */
    { 0,     48, PRIME64, 0xADC2CBAA44ACC616ULL },  /* 33 - 64 */
    { 0,     80,       0, 0xBCDEFBBB2C47C90AULL },  /* 65 - 96 */
    { 0,     80, PRIME64, 0xC6DD0CB699532E73ULL },  /* 65 - 96 */
    { 0,    195,       0, 0xCD94217EE362EC3AULL },  /* 129-240 */
    { 0,    195, PRIME64, 0xBA68003D370CB3D9ULL },  /* 129-240 */

    { 0,    403,       0, 0xCDEB804D65C6DEA4ULL },  /* one block, last stripe is overlapping */
    { 0,    403, PRIME64, 0x6259F6ECFD6443FDULL },  /* one block, last stripe is overlapping */
    { 0,    512,       0, 0x617E49599013CB6BULL },  /* one block, finishing at stripe boundary */
    { 0,    512, PRIME64, 0x3CE457DE14C27708ULL },  /* one block, finishing at stripe boundary */
    { 0,   2048,       0, 0xDD59E2C3A5F038E0ULL },  /* 2 blocks, finishing at block boundary */
    { 0,   2048, PRIME64, 0x66F81670669ABABCULL },  /* 2 blocks, finishing at block boundary */
    { 0,   2240,       0, 0x6E73A90539CF2948ULL },  /* 3 blocks, finishing at stripe boundary */
    { 0,   2240, PRIME64, 0x757BA8487D1B5247ULL },  /* 3 blocks, finishing at stripe boundary */
    { 0,   2367,       0, 0xCB37AEB9E5D361EDULL },  /* 3 blocks, last stripe is overlapping */
    { 0,   2367, PRIME64, 0xD2DB3415B942B42AULL }   /* 3 blocks, last stripe is overlapping */
};

static const XSUM_testdata64_t XSUM_XXH3_withSecret_testdata[] = {
    { 1,       0, 0, 0x3559D64878C5C66CULL },  /* empty string */
    { 0,       1, 0, 0x8A52451418B2DA4DULL },  /*  1 -  3 */
    { 0,       6, 0, 0x82C90AB0519369ADULL },  /*  4 -  8 */
    { 0,      12, 0, 0x14631E773B78EC57ULL },  /*  9 - 16 */
    { 0,      24, 0, 0xCDD5542E4A9D9FE8ULL },  /* 17 - 32 */
    { 0,      48, 0, 0x33ABD54D094B2534ULL },  /* 33 - 64 */
    { 0,      80, 0, 0xE687BA1684965297ULL },  /* 65 - 96 */
    { 0,     195, 0, 0xA057273F5EECFB20ULL },  /* 129-240 */

    { 0,     403, 0, 0x14546019124D43B8ULL },  /* one block, last stripe is overlapping */
    { 0,     512, 0, 0x7564693DD526E28DULL },  /* one block, finishing at stripe boundary */
    { 0,    2048, 0, 0xD32E975821D6519FULL },  /* >= 2 blocks, at least one scrambling */
    { 0,    2367, 0, 0x293FA8E5173BB5E7ULL },  /* >= 2 blocks, at least one scrambling, last stripe unaligned */

    { 0, 64*10*3, 0, 0x751D2EC54BC6038BULL }   /* exactly 3 full blocks, not a multiple of 256 */
};

static const XSUM_testdata128_t XSUM_XXH128_testdata[] = {
    { 1,      0,       0, { 0x6001C324468D497FULL, 0x99AA06D3014798D8ULL } },  /* empty string */
    { 1,      0, PRIME32, { 0x5444F7869C671AB0ULL, 0x92220AE55E14AB50ULL } },  /* empty string */
    { 0,      1,       0, { 0xC44BDFF4074EECDBULL, 0xA6CD5E9392000F6AULL } },  /*  1 -  3 */
    { 0,      1, PRIME32, { 0xB53D5557E7F76F8DULL, 0x89B99554BA22467CULL } },  /*  1 -  3 */
    { 0,      6,       0, { 0x3E7039BDDA43CFC6ULL, 0x082AFE0B8162D12AULL } },  /*  4 -  8 */
    { 0,      6, PRIME32, { 0x269D8F70BE98856EULL, 0x5A865B5389ABD2B1ULL } },  /*  4 -  8 */
    { 0,     12,       0, { 0x061A192713F69AD9ULL, 0x6E3EFD8FC7802B18ULL } },  /*  9 - 16 */
    { 0,     12, PRIME32, { 0x9BE9F9A67F3C7DFBULL, 0xD7E09D518A3405D3ULL } },  /*  9 - 16 */
    { 0,     24,       0, { 0x1E7044D28B1B901DULL, 0x0CE966E4678D3761ULL } },  /* 17 - 32 */
    { 0,     24, PRIME32, { 0xD7304C54EBAD40A9ULL, 0x3162026714A6A243ULL } },  /* 17 - 32 */
    { 0,     48,       0, { 0xF942219AED80F67BULL, 0xA002AC4E5478227EULL } },  /* 33 - 64 */
    { 0,     48, PRIME32, { 0x7BA3C3E453A1934EULL, 0x163ADDE36C072295ULL } },  /* 33 - 64 */
    { 0,     81,       0, { 0x5E8BAFB9F95FB803ULL, 0x4952F58181AB0042ULL } },  /* 65 - 96 */
    { 0,     81, PRIME32, { 0x703FBB3D7A5F755CULL, 0x2724EC7ADC750FB6ULL } },  /* 65 - 96 */
    { 0,    222,       0, { 0xF1AEBD597CEC6B3AULL, 0x337E09641B948717ULL } },  /* 129-240 */
    { 0,    222, PRIME32, { 0xAE995BB8AF917A8DULL, 0x91820016621E97F1ULL } },  /* 129-240 */

    { 0,    403,       0, { 0xCDEB804D65C6DEA4ULL, 0x1B6DE21E332DD73DULL } },  /* one block, last stripe is overlapping */
    { 0,    403, PRIME64, { 0x6259F6ECFD6443FDULL, 0xBED311971E0BE8F2ULL } },  /* one block, last stripe is overlapping */
    { 0,    512,       0, { 0x617E49599013CB6BULL, 0x18D2D110DCC9BCA1ULL } },  /* one block, finishing at stripe boundary */
    { 0,    512, PRIME64, { 0x3CE457DE14C27708ULL, 0x925D06B8EC5B8040ULL } },  /* one block, finishing at stripe boundary */
    { 0,   2048,       0, { 0xDD59E2C3A5F038E0ULL, 0xF736557FD47073A5ULL } },  /* 2 blocks, finishing at block boundary */
    { 0,   2048, PRIME32, { 0x230D43F30206260BULL, 0x7FB03F7E7186C3EAULL } },  /* 2 blocks, finishing at block boundary */
    { 0,   2240,       0, { 0x6E73A90539CF2948ULL, 0xCCB134FBFA7CE49DULL } },  /* 3 blocks, finishing at stripe boundary */
    { 0,   2240, PRIME32, { 0xED385111126FBA6FULL, 0x50A1FE17B338995FULL } },  /* 3 blocks, finishing at stripe boundary */
    { 0,   2367,       0, { 0xCB37AEB9E5D361EDULL, 0xE89C0F6FF369B427ULL } },  /* 3 blocks, last stripe is overlapping */
    { 0,   2367, PRIME32, { 0x6F5360AE69C2F406ULL, 0xD23AAE4B76C31ECBULL } }   /* 3 blocks, last stripe is overlapping */
};
```

**Comment by Cyan4973** [comment]
Yes, it's much better

**Review by Cyan4973 — APPROVED** [review]

**Comment by easyaspi314** [comment]
Before I start working on the benchmark, should I switch the benchmark to use the more precise counters from `tests/bench/timefn.c`?

**Comment by Cyan4973** [comment]
That's a good idea.
It's certainly easier to do now, and is supposed to help with regards to measurements accuracy.

**Pull request merged**
