### PR TITLE
Use __builtin_rotate on Clang

### PR DESCRIPTION
**Pull request by easyaspi314**

### CODE REVIEW

**Comment by easyaspi314** [comment]
Can you squeeze this in?

**Comment by Cyan4973** [comment]
Are there any other patch you wish to include before cutting a new release ?

The `VSX` code path, for example ? It's currently disabled, as a modification is needed to make it work for both 64 and 128 bits variants.

Also, does your change regarding `__builtin_rotate*()` make any impact on the `clang` inefficiency you reported ?

**Comment by easyaspi314** [comment]
> Also, does your change regarding __builtin_rotate*() make any impact on the clang inefficiency you reported ?

Yes. The codegen is a LOT cleaner for XXH64_finalize().

> The VSX code path, for example ? It's currently disabled, as a modification is needed to make it work for both 64 and 128 bits variants.

I'll try to have it fixed by tomorrow. 

Also, I say we remove the `#pragma clang loop unroll(enable)`. It doesn't seem to b
```c
$ clang -O3 -S xxhash.c
In file included from xxhash.c:1115:
./xxh3.h:861:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
XXH3_hashLong_64b_defaultSecret(const void* XXH_RESTRICT data, size_t len)
^
./xxh3.h:867:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
XXH3_hashLong_64b_withSecret(const void* XXH_RESTRICT data, size_t len,
^
./xxh3.h:867:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
./xxh3.h:907:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
XXH3_hashLong_64b_withSeed(const void* data, size_t len, XXH64_hash_t seed)
^
./xxh3.h:1176:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
XXH3_64bits_update(XXH3_state_t* state, const void* input, size_t len)
^
./xxh3.h:1176:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
./xxh3.h:1176:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
./xxh3.h:1176:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
./xxh3.h:1213:29: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
XXH_PUBLIC_API XXH64_hash_t XXH3_64bits_digest (const XXH3_state_t* state)
                            ^
./xxh3.h:1213:29: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
./xxh3.h:1213:29: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
./xxh3.h:1327:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
XXH3_hashLong_128b_defaultSecret(const void* data, size_t len)
^
./xxh3.h:1333:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
XXH3_hashLong_128b_withSecret(const void* data, size_t len,
^
./xxh3.h:1333:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
./xxh3.h:1340:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
XXH3_hashLong_128b_withSeed(const void* data, size_t len, XXH64_hash_t seed)
^
./xxh3.h:1503:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
XXH3_128bits_update(XXH3_state_t* state, const void* input, size_t len)
^
./xxh3.h:1503:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
./xxh3.h:1503:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
./xxh3.h:1503:1: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
./xxh3.h:1508:30: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
XXH_PUBLIC_API XXH128_hash_t XXH3_128bits_digest (const XXH3_state_t* state)
                             ^
./xxh3.h:1508:30: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
./xxh3.h:1508:30: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering
      [-Wpass-failed=transform-warning]
22 warnings generated.
```

**Comment by Cyan4973** [comment]
These are good suggestions

**Comment by Cyan4973** [comment]
I'll have to move on, so I'll publish xxhash v0.7.1 later today even without these patches.
Don't worry though, the code base is obviously not static, and can still accept patches after the merge.

**Pull request merged**
