### PR TITLE
Document some nerdy ARM stuff, move scalarRound down.

### PR DESCRIPTION
**Pull request by easyaspi314**
- Mentioned how the XXH3_NEON_LANES optimization only helps CPUs with large micro-op buffers. 
- Moved the scalarRound and scalarScrambleRound functions back to the bottom.

### CODE REVIEW

**Comment by easyaspi314** [comment]
you saw nothing
Screenshot_20211202-121458

**Comment by easyaspi314** [comment]
~~can you tell I wrote this late at night?~~

**Review by Cyan4973 — APPROVED** [review]

**Comment by Cyan4973** [comment]
Great explanations, as always @easyaspi314 !

**Comment by easyaspi314** [comment]
I just noticed that I made yet another typo.

This is what I get for coding on my phone. 🤦

**Pull request merged**
