### PR TITLE
add a test combining Windows + Visual + Clang-Cl + DISPATCH=1

### PR DESCRIPTION
**Pull request by Cyan4973**
test that #763 is fixed and remains fixed

### CODE REVIEW

**Comment by t-mat** [comment]
https://github.com/Cyan4973/xxHash/actions/runs/5562735680/jobs/10161223314?pr=863#step:7:15

Since we don't see the `"Enable xxHash dispatch mode"` message from the following block, it seems it doesn't work properly.

https://github.com/Cyan4973/xxHash/blob/4fd75d7bdd7f5e4562ce4b38af8e4c414ab194e2/cmake_unofficial/CMakeLists.txt#L88-L94

**Comment by Cyan4973** [comment]
mmmh, that doesn't work.
The generated `xxhsum` binary [still doesn't use `DISPATCH`](https://github.com/Cyan4973/xxHash/actions/runs/5562735680/jobs/10161223314?pr=863#step:8:6) despite setting `-DDISPATCH=1` at `cmake` build time.

Strangely, the same command seems to work fine in local tests on Ubuntu.
So maybe this could be related to the `Windows` + `Visual Studio` environment (?)

**Comment by t-mat** [comment]
It seems the actual Architecture (`${PLATFORM}`) for MSVC x86_64 is `AMD64`

https://github.com/Cyan4973/xxHash/actions/runs/5562735680/jobs/10161223314?pr=863#step:7:22

```
-- Detecting C compile features - done
-- Architecture: AMD64
-- Configuring done (2.5s)
```

The following patch for `cmake_unofficial/CMakeList.txt` enables dispatch mode for clang-cl.

```diff
# Only support DISPATCH option on x86_64.
- if("${PLATFORM}" STREQUAL "x86_64")
+ if(("${PLATFORM}" STREQUAL "x86_64") OR ("${PLATFORM}" STREQUAL "AMD64"))
```

But it may cause error.  See also https://github.com/Cyan4973/xxHash/issues/763#issuecomment-1636781578

**Comment by t-mat** [comment]
After #865, this PR should work properly.

**Comment by Cyan4973** [comment]
rebasing on top of @t-mat 's #865

**Comment by Cyan4973** [comment]
This works great ! Thanks @t-mat !

The test will now also properly fail with a clear error signal if the produced `xxhsum` binary is not `autoVec`.

**Comment by t-mat** [comment]
https://github.com/Cyan4973/xxHash/actions/runs/5564095301/jobs/10163482759#step:7:25

```
-- Enable xxHash dispatch mode
```

https://github.com/Cyan4973/xxHash/actions/runs/5564095444/jobs/10163482094?pr=863#step:8:7

```
compiled as 64-bit x86_64 autoVec little endian with Clang 12.0.0  
```

🥳

**Pull request merged**
