### PR TITLE
fixed performance issue reported in #398

### PR DESCRIPTION
**Pull request by Cyan4973**
note :
I was unable to reproduce the speed issue on my own platforms (laptop, desktop, macos, ubuntu).
Therefore, @easyaspi314, could you test that this patch solves your performance issue ?

The fix feels logical enough, and doesn't negatively impact performance either, so even if I can't observe performance benefits directly, it's good to go.

Perhaps more importantly : 
this patch also fixes `XXH128_withSecret()`,
which was messed up with default `kSecret`.
The error remained unnoticed because there was no self-test for this variant.
Therefore, also added a test in `xxhsum` checking results of `XXH128_withSecret()`

### CODE REVIEW

**Comment by easyaspi314** [comment]
I will test performance tomorrow.

I did realize that the performance difference happened when adding XXH32 and XXH64's streaming variants to the table...which somehow made a difference to XXH3. 🤔

**Comment by Cyan4973** [comment]
> I did realize that the performance difference happened when adding XXH32 and XXH64's streaming variants to the table...which somehow made a difference to XXH3.

Instructions alignment ?...

**Comment by easyaspi314** [comment]
Possibly, I believe my MacBook might have the loop alignment errata. It is really strange though. 

Either way, nice find on the XXH128 bug…imagine if that got to v0.7.4...

**Comment by Cyan4973** [comment]
I'm still interested to know the impact of this PR on your system.
In the meantime, since I believe there is no downside to this PR, and it also fixes another nasty problem related to `XXH128_withSecret()`, I'll merge it.

**Pull request merged**
